name: Tag

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    environment: production

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      deployments: write

    env:
      VERSION: "1.0.${{ github.run_number }}-${{ github.run_attempt }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tag Version
        if: success()
        run: git tag ${{ env.VERSION }} && git push --tags
        shell: bash
